### ISSUE TITLE
Requirements for queue-redis implementation

### ISSUE THREAD

**Issue by g41797** [yiisoft/queue-redis#1]
### What is the expected result?
"SRS" for queue-redis

**Comment by samdark** [comment]
It should be implementation of [yiisoft/queue](https://github.com/yiisoft/queue) same as [yiisoft/queue-amqp](https://github.com/yiisoft/queue-amqp).

There's Yii2 implementation for Redis: https://github.com/yiisoft/yii2-queue/blob/master/src/drivers/redis/Queue.php It worked but could be improved.

**Comment by g41797** [comment]
did you mean [Migrating from yii2-queue](https://github.com/yiisoft/queue/blob/master/docs/guide/migrating-from-yii2-queue.md#migrating-from-yii2-queue)?
or [Add ability to set message headers](https://github.com/yiisoft/queue-amqp/issues/57)
there are 19 not closed redis related issues in [yii2-queue](https://github.com/yiisoft/yii2-queue) - also should be taken upon consideration?
i understand that working with outsourcer requires additional time, but requirements above require additional information
how can we continue?

**Comment by samdark** [comment]
> there are 19 not closed redis related issues in [yii2-queue](https://github.com/yiisoft/yii2-queue) - also should be taken upon consideration?

Yes. That's not a direct 1 to 1 port so any improvement or even a new way of doing things are welcome.

**Comment by samdark** [comment]
> i understand that working with outsourcer requires additional time, but requirements above require additional information
how can we continue?

Ask questions.

**Comment by g41797** [comment]
regarding new way - already send dm to slack [Using CloudEvents in YiiQueue](https://yii.slack.com/archives/D06DSHBJXEX/p1705308984912379)

**Comment by g41797** [comment]
> Ask questions

What is the deadline ?

**Comment by samdark** [comment]
Deadline for the driver? Well, as soon as possible.

**Comment by g41797** [comment]
it can't be fast with my php knowledge
