### ISSUE TITLE
[Questions]Regarding Adapter implementation

### ISSUE THREAD

**Issue by g41797** [yiisoft/queue-redis#4]
1. What is the reason not to use LoopInterface within _runExisting_ method?
2. Is there any example of Adapter's definition in the channel-definitions params key to be used with the [queue factory](https://github.com/yiisoft/queue#different-queue-channels)?
3. LoopInterface is the parametor for creation of Adapter. Does it mean that Adapter and Queue can use different implementations?
4. Are you going to use non-default Redis configuration (at least _username_ and _password_)?

Thanks

**Comment by TalismanFR** [comment]
Hello @g41797 !
Thanks for your interest in the library code! 🙂
1. I coded this adapter based on the [amqp](https://github.com/yiisoft/queue-amqp/blob/master/src/Adapter.php#L35) adapter and having little time to implement it. Before your question, I didn’t have time to think about the need for a LoopInterface in this method 😉 It looks like Loop needed there too.

3. I'm not sure I understood the question correctly. Defining adapter parameters both in the factory and in the DI will be similar.
In the simplest case it might look like this:
```php
use Yiisoft\Queue\Adapter\AdapterInterface;
use Yiisoft\Queue\Redis\Adapter;
[
            'channel1' => [
                'class' => Adapter::class,
            ],
            'channel2' => static fn(AdapterInterface $adapter) => $adapter->withChannel('channel2'),
        ];
```
4. In theory this is possible. It’s hard to say whether it’s necessary in practice)
5. The configuration of the `\Redis` object can be any and does not depend on the adapter. The main thing is that it is connected.
