### ISSUE TITLE
[Question] DI definition for Adapter

### ISSUE THREAD

**Issue by g41797** [yiisoft/queue-redis#5]
queue-redis Adapter 'ctor':
```php
    public function __construct(
        private QueueProviderInterface $provider,
        private MessageSerializerInterface $serializer,
        private LoopInterface $loop,
        private int $timeout = 3
    ) {
```

di definition:
```php

return [
    \Yiisoft\Queue\Redis\QueueProviderInterface::class => \Yiisoft\Queue\Redis\QueueProvider::class,
];
```

Why serializer, loop and provider were not defined?

I used this repo as prototype for [NATS adapter](https://github.com/g41797/queue-nats) and still don't understand how to create di definitions

**Comment by samdark** [comment]
@TalismanFR need your input.

**Comment by xepozz** [comment]
Provider's definition is [there](https://github.com/yiisoft/queue-redis/blob/master/config/di.php), you mentioned it.
Serializer is used [from the main repo](https://github.com/yiisoft/queue/blob/master/config/di.php#L59) and there are no need to redefine not changed definition.
The same thing with [the loop](https://github.com/yiisoft/queue/blob/master/config/di.php#L37)
